# Generated by Django 4.1.3 on 2022-12-26 22:04

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_setting_aboutus_alter_setting_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='aboutus',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=2000),
        ),
    ]
