# Generated by Django 4.1.3 on 2022-12-26 22:24

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_setting_aboutus'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='faq',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=2000),
        ),
    ]
