# Generated by Django 4.1.3 on 2022-12-26 22:35

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_setting_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='contact',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=2000),
        ),
    ]
